### ISSUE TITLE
Bundle Dependencies

### ISSUE THREAD

**Issue by spuder** [spuder/simple-ynab#4]
The gem on rubygems doesn't include any dependencies. This causes an error on brand new systems. 

```bash
rvm install 2.2.0
....
spencerowen@Spencers-MBP:~/chef-repo$ simple-ynab -v -x -y -d 40 ~/Downloads/2015-01-04-exported_transactions.csv 
/Users/spencerowen/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- slop (LoadError)
	from /Users/spencerowen/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/spencerowen/.rvm/gems/ruby-2.2.0/gems/simple-ynab-0.1.0/bin/simple-ynab:5:in `<top (required)>'
	from /Users/spencerowen/.rvm/gems/ruby-2.2.0/bin/simple-ynab:23:in `load'
	from /Users/spencerowen/.rvm/gems/ruby-2.2.0/bin/simple-ynab:23:in `<main>'
	from /Users/spencerowen/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/spencerowen/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

The solution is to run `gem install slop`, `gem install colorize`, this should be included in the gem dependencies

**Comment by spuder** [comment]
fixed in 0.1.1
